name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2


    # - name: pouch  detection-intrusion workshop
    #   uses: pushou/copy_file_to_another_repo_action@main
    #   env:
    #       API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    #   with:
    #     source_file: './pdfs/workshop-detection-intrusion-reseaux.pdf'
    #     destination_repo: 'pushou/pushou_public_pdf'
    #     user_email: 'jean-marc.pouchoulon@umontpellier.fr'
    #     user_name: 'pushou'
    #     commit_message: 'new detection-intrusion pdf build'


    # - name: pouch  detection-intrusion corrige workshop
    #   uses: pushou/copy_file_to_another_repo_action@main
    #   env:
    #       API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    #   with:
    #     source_file: './pdfs/workshop-detection-intrusion-reseaux-elements-de-correction.pdf'
    #     destination_repo: 'pushou/workshop-avec-elem-cor'
    #     user_email: 'jean-marc.pouchoulon@umontpellier.fr'
    #     user_name: 'pushou'
    #     commit_message: 'new detection-intrusion pdf build'

#####################################################################
# cours
    - name: pouch  infra as code
      uses: pushou/copy_file_to_another_repo_action@main
      env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: './pdfs/infrastructure-as-code.pdf'
        destination_repo: 'pushou/pushou_public_pdf'
        destination_folder: 'BUT/R5.devcloud.11'
        user_email: 'jean-marc.pouchoulon@umontpellier.fr'
        user_name: 'pushou'
        commit_message: 'new intro detection intrusion pdf build'


    - name: pouch  TP vagrant
      uses: pushou/copy_file_to_another_repo_action@main
      env:
         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: './pdfs/TP-vagrant.pdf'
        destination_repo: 'pushou/pushou_public_pdf'
        destination_folder: 'BUT/R3.devcloud.17'
        user_email: 'jean-marc.pouchoulon@umontpellier.fr'
        user_name: 'pushou'
        commit_message: 'new TP Vagrant pdf build'
        
    - name: pouch  TP Packer
      uses: pushou/copy_file_to_another_repo_action@main
      env:
       API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: './pdfs/TP-packer.pdf'
        destination_repo: 'pushou/pushou_public_pdf'
        destination_folder: 'BUT/R5.devcloud.11'
        user_email: 'jean-marc.pouchoulon@umontpellier.fr'
        user_name: 'pushou'
        commit_message: 'new TP Packer pdf build'

    - name: pouch  TP vagrant windows
      uses: pushou/copy_file_to_another_repo_action@main
      env:
       API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: './pdfs/TP-vagrant-windows.pdf'
        destination_repo: 'pushou/pushou_public_pdf'
        destination_folder: 'BUT/R5.devcloud.11'
        user_email: 'jean-marc.pouchoulon@umontpellier.fr'
        user_name: 'pushou'
        commit_message: 'new TP Packer pdf vagrant-windows'

    - name: pouch  TP Terraform
      uses: pushou/copy_file_to_another_repo_action@main
      env:
       API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
          source_file: './pdfs/TP-terraform.pdf'
          destination_repo: 'pushou/pushou_public_pdf'
          destination_folder: 'BUT/R5.devcloud.11'
          user_email: 'jean-marc.pouchoulon@umontpellier.fr'
          user_name: 'pushou'
          commit_message: 'new TP Terraform'
  
  #   - name: pouch  techno supervision windows
  #     uses: pushou/copy_file_to_another_repo_action@main
  #     env:
  #       API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #     with:
  #       source_file: './pdfs/Evenements-sous-windows.pdf'
  #       destination_repo: 'pushou/pushou_public_pdf'
  #       destination_folder: 'BUT/R5.cyber.11'
  #       user_email: 'jean-marc.pouchoulon@umontpellier.fr'
  #       user_name: 'pushou'
  #       commit_message: 'new techno supervision intrusion windows pdf build'
    
  #   - name: pouch  intro Kerberos
  #     uses: pushou/copy_file_to_another_repo_action@main
  #     env:
  #       API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #     with:
  #       source_file: './pdfs/cours-kerberos.pdf'
  #       destination_repo: 'pushou/pushou_public_pdf'
  #       destination_folder: 'BUT/R5.cyber.11'
  #       user_email: 'jean-marc.pouchoulon@umontpellier.fr'
  #       user_name: 'pushou'
  #       commit_message: 'new kerberos pdf build'

  # ####################################################################
  # # tuto en images

  #   - name: pouch  join ad domain
  #     uses: pushou/copy_file_to_another_repo_action@main
  #     env:
  #       API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #     with:
  #       source_file: './pdfs/join_domain_en_images.pdf'
  #       destination_repo: 'pushou/pushou_public_pdf'
  #       destination_folder: 'BUT/R5.cyber.11'
  #       user_email: 'jean-marc.pouchoulon@umontpellier.fr'
  #       user_name: 'pushou'
  #       commit_message: 'new  join ad domain'

  #   - name: pouch  install AD
  #     uses: pushou/copy_file_to_another_repo_action@main
  #     env:
  #       API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #     with:
  #       source_file: './pdfs/installation_ad_en_images.pdf'
  #       destination_repo: 'pushou/pushou_public_pdf'
  #       destination_folder: 'BUT/R5.cyber.11'
  #       user_email: 'jean-marc.pouchoulon@umontpellier.fr'
  #       user_name: 'pushou'
  #       commit_message: 'new installation AD en images'

  #   - name: pouch  gpo wef
  #     uses: pushou/copy_file_to_another_repo_action@main
  #     env:
  #         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #     with:
  #       source_file: './pdfs/installation_wef_policy_en_images.pdf'
  #       destination_repo: 'pushou/pushou_public_pdf'
  #       destination_folder: 'BUT/R5.cyber.11'
  #       user_email: 'jean-marc.pouchoulon@umontpellier.fr'
  #       user_name: 'pushou'
  #       commit_message: 'new installation GPO wef en images'
    
    
  #   - name: pouch  wec server
  #     uses: pushou/copy_file_to_another_repo_action@main
  #     env:
  #         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #     with:
  #       source_file: './pdfs/installation_wec.pdf'
  #       destination_repo: 'pushou/pushou_public_pdf'
  #       destination_folder: 'BUT/R5.cyber.11'
  #       user_email: 'jean-marc.pouchoulon@umontpellier.fr'
  #       user_name: 'pushou'
  #       commit_message: 'new installation wec en images'
 
  #   - name: pouch  elastic
  #     uses: pushou/copy_file_to_another_repo_action@main
  #     env:
  #         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  #     with:
  #       source_file: './pdfs/TP-ELASTIC.pdf'
  #       destination_repo: 'pushou/pushou_public_pdf'
  #       destination_folder: 'BUT/R5.cyber.11'
  #       user_email: 'jean-marc.pouchoulon@umontpellier.fr'
  #       user_name: 'pushou'
  #       commit_message: 'new TP elastic'
    

####################################################################
# TD

#     - name: pouch  TD sigma rules
#       uses: pushou/copy_file_to_another_repo_action@main
#       env:
#         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#       with:
#         source_file: './pdfs/TD-sigma_rules.pdf'
#         destination_repo: 'pushou/pushou_public_pdf'
#         destination_folder: 'BUT/R5.cyber.11'
#         user_email: 'jean-marc.pouchoulon@umontpellier.fr'
#         user_name: 'pushou'
#         commit_message: 'new sigma rule intrusion windows pdf build'
    
#     - name: pouch  TD base windows AD
#       uses: pushou/copy_file_to_another_repo_action@main
#       env:
#         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#       with:
#         source_file: './pdfs/TD-sigma_rules.pdf'
#         destination_repo: 'pushou/pushou_public_pdf'
#         destination_folder: 'BUT/R5.cyber.11'
#         user_email: 'jean-marc.pouchoulon@umontpellier.fr'
#         user_name: 'pushou'
#         commit_message: 'new sigma rule intrusion windows pdf build'

#     - name: pouch  TD Chainsaw et Hayabusa
#       uses: pushou/copy_file_to_another_repo_action@main
#       env:
#         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#       with:
#         source_file: './pdfs/TD-sigma-app.pdf'
#         destination_repo: 'pushou/pushou_public_pdf'
#         destination_folder: 'BUT/R5.cyber.11'
#         user_email: 'jean-marc.pouchoulon@umontpellier.fr'
#         user_name: 'pushou'
#         commit_message: 'new chainsaw hayabusa pdf build'
  
    
# ####################################################################
# # TP

#     - name: pouch  domain base
#       uses: pushou/copy_file_to_another_repo_action@main
#       env:
#             API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#       with:
#           source_file: './pdfs/TP-DOMAINBASE.pdf'
#           destination_repo: 'pushou/pushou_public_pdf'
#           destination_folder: 'BUT/R5.cyber.11'
#           user_email: 'jean-marc.pouchoulon@umontpellier.fr'
#           user_name: 'pushou'
#           commit_message: 'new Domain Base'    

#     - name: TP WEC WEF
#       uses: pushou/copy_file_to_another_repo_action@main
#       env:
#             API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#       with:
#           source_file: './pdfs/TP-WEC-WEF.pdf'
#           destination_repo: 'pushou/pushou_public_pdf'
#           destination_folder: 'BUT/R5.cyber.11'
#           user_email: 'jean-marc.pouchoulon@umontpellier.fr'
#           user_name: 'pushou'
#           commit_message: 'new TP wec wef'    

#     - name: TP detection intrusion
#       uses: pushou/copy_file_to_another_repo_action@main
#       env:
#           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#       with:
#           source_file: './pdfs/TP-detection-intrusion-reseaux.pdf'
#           destination_repo: 'pushou/pushou_public_pdf'
#           destination_folder: 'BUT/R5.cyber.11'
#           user_email: 'jean-marc.pouchoulon@umontpellier.fr'
#           user_name: 'pushou'
#           commit_message: 'new TP detection intrusion r√©seau'    


#     - name: TP Wazuh auditd tpot suricata
#       uses: pushou/copy_file_to_another_repo_action@main
#       env:
#           API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#       with:
#           source_file: './pdfs/TP-WAZUH-AUDITD-TPOT-SURICATA.pdf'
#           destination_repo: 'pushou/pushou_public_pdf'
#           destination_folder: 'BUT/R5.cyber.11'
#           user_email: 'jean-marc.pouchoulon@umontpellier.fr'
#           user_name: 'pushou'
#           commit_message: 'new Wazuh auditd tpot suricata' 

  